# Generated by Django 3.2.8 on 2021-11-07 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serwis', models.BooleanField(default=False)),
                ('aktywny', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RodzajUsterki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj_usterki', models.CharField(max_length=60)),
                ('aktywny', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Serwisant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_serwisanta', models.DecimalField(decimal_places=0, max_digits=4, unique=True)),
                ('imie', models.CharField(max_length=80)),
                ('nazwisko', models.CharField(max_length=80)),
                ('aktywny', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=40, unique=True)),
                ('aktywny', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Urzadzenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_urzadzenia', models.CharField(max_length=80)),
                ('aktywny', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zgloszenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj', models.CharField(max_length=60, unique=True)),
                ('data_zgloszenia', models.DateField(verbose_name='data zgłoszenia')),
                ('czas_zgloszenia', models.TimeField(verbose_name='czas zgłoszenia')),
                ('temat_zgloszenia', models.CharField(max_length=400)),
                ('opis_zgloszenia', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'Nowy'), (3, 'Czeka na wyjaśnienie'), (5, 'Anulowany'), (2, 'Otwarty'), (4, 'Zamknięty')], default=1)),
                ('data_otwarcia', models.DateField(blank=True, default='1900-01-01', null=True, verbose_name='data otwarcia')),
                ('czas_otwarcia', models.TimeField(blank=True, default='00:00', null=True, verbose_name='czas otwarcia')),
                ('data_zamkniecia', models.DateField(blank=True, default='1900-01-01', null=True, verbose_name='data zamknięcia')),
                ('czas_zamkniecia', models.TimeField(blank=True, default='00:00', null=True, verbose_name='czas zamknięcia')),
                ('rodzaj_usterki', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='serwis.rodzajusterki')),
                ('serwisant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serwisant', to='serwis.autor')),
                ('urzadzenie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='serwis.urzadzenie')),
                ('zglaszajacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zglaszajacy', to='serwis.autor')),
            ],
        ),
    ]
