# Generated by Django 3.2.8 on 2021-10-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serwis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urzadzenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_urzadzenia', models.CharField(max_length=80)),
                ('aktywny', models.BooleanField(default=True)),
            ],
        ),
    ]
