# Generated by Django 3.2.8 on 2021-11-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serwis', '0002_alter_zgloszenie_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zgloszenie',
            name='rodzaj',
        ),
        migrations.AlterField(
            model_name='zgloszenie',
            name='status',
            field=models.IntegerField(choices=[(2, 'Otwarty'), (1, 'Nowy'), (4, 'Zamknięty'), (3, 'Czeka na wyjaśnienie'), (5, 'Anulowany')], default=1),
        ),
    ]
