# Generated by Django 3.2.8 on 2021-10-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serwis', '0002_urzadzenie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serwisant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_serwisanta', models.DecimalField(decimal_places=0, max_digits=4, unique=True)),
                ('imie', models.CharField(max_length=80)),
                ('nazwisko', models.CharField(max_length=80)),
                ('aktywny', models.BooleanField(default=True)),
            ],
        ),
    ]
