# Generated by Django 3.2.8 on 2021-10-27 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serwis', '0003_serwisant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='serwisant',
        ),
        migrations.CreateModel(
            name='Zgloszenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zgloszenia', models.DateField(verbose_name='data zgłoszenia')),
                ('temat_zgloszenia', models.CharField(max_length=400)),
                ('opis_zgloszenia', models.TextField()),
                ('zglaszajacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serwis.autor')),
            ],
        ),
    ]
