# Generated by Django 3.2.8 on 2021-10-28 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serwis', '0004_auto_20211027_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='zgloszenie',
            name='czas_zgloszenia',
            field=models.TimeField(default='00:00:00', verbose_name='czas zgłoszenia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zgloszenie',
            name='rodzaj_usterki',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='serwis.rodzajusterki'),
        ),
        migrations.AddField(
            model_name='zgloszenie',
            name='urzadzenie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='serwis.urzadzenie'),
        ),
    ]
