# Generated by Django 3.2.8 on 2021-10-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serwis', '0005_auto_20211028_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=40, unique=True)),
                ('aktywny', models.BooleanField(default=True)),
            ],
        ),
    ]
