# Generated by Django 3.2.8 on 2021-10-28 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serwis', '0006_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='zgloszenie',
            name='czas_otwarcia',
            field=models.TimeField(default='00:00:00', verbose_name='czas otwarcia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zgloszenie',
            name='czas_zamkniecia',
            field=models.TimeField(default='00:00:00', verbose_name='czas zamknięcia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zgloszenie',
            name='data_otwarcia',
            field=models.DateField(default='1900-01-01', verbose_name='data otwarcia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zgloszenie',
            name='data_zamkniecia',
            field=models.DateField(default='1900-01-01', verbose_name='data zamknięcia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zgloszenie',
            name='serwisant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='serwis.serwisant'),
        ),
        migrations.AddField(
            model_name='zgloszenie',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='serwis.status'),
        ),
    ]
